apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-server
    app.kubernetes.io/instance: adjust-http-server
  name: http-server
  namespace: http-server
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: http-server
  type: ClusterIP
